% Plot creation for comparing the genetic algorithm-based feature selection
% to predictions using the full feature set.

function featureSelectionPlots
    % N is the number of data points (repetitions of myFeatureSelectionWithGA)
    N = 100;
    % Column 1: accuracies with GA, column 2: accuracies without GA
    accuracies = zeros(N,2);
    % Number of features of the best chromosome, indexed the same as
    % accuracies
    numFeatures = zeros(N,1);
    for i=1:N
        fprintf("run %d of %d\n", i, N);
        [bestChromosome, acc1, acc2] = myFeatureSelectionwithGA();
        accuracies(i,:) = [acc1, acc2];
        numFeatures(i) = sum(bestChromosome);
    end
    % Clear figures generated by genetic algorithm
    clf;
    figure;
    % First plot: accuracies across runs, one boxplot
    subplot(1,2,1);
    groups = string(zeros(1, 2*N));
    groups(1:N) = "Selected features";
    groups(N+1:end) = "All features";
    boxplot(reshape(accuracies, [1, 2*N]), groups);
    ylabel("Accuracy");
    title("Accuracy distribution of feature selection");
    % Mapping from number of features to array of accuracies gained by
    % using the number of features
    featAccMap = containers.Map('KeyType','uint32', 'ValueType','any');
    for i=1:N
        feat = numFeatures(i);
        if isKey(featAccMap, feat)
            featAccMap(feat) = [featAccMap(feat), accuracies(i,1)];
        else
            featAccMap(feat) = accuracies(i,1);
        end
    end
    % Second plot: accuracy against number of features used to make the
    % prediction, one boxplot per unique number of features used
    subplot(1,2,2)
    accCells = values(featAccMap);
    features = cell2mat(keys(featAccMap));
    % Define groups for boxplots
    groupSizes = cellfun(@length, accCells);
    groups = zeros(1, sum(groupSizes));
    j = 1;
    for i=1:length(groupSizes)
        groups(1,j:j+groupSizes(i)-1) = features(i);
        j = j + groupSizes(i);
    end
    boxplot(cell2mat(accCells), groups);
    xlabel('Number of features');
    ylabel('Accuracy');
    title("Accuracy against number of features used to make prediction");
    drawnow;